version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: db_shareat
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shareat
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d shareat" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-non-dev
    command: ["/app/docker/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - s3
    restart: unless-stopped

  s3:
    image: bitnami/minio:latest
    container_name: s3_service
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
      - ./docker/create-bucket.sh:/usr/local/bin/create-bucket.sh
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address \":9001\" &
      sleep 5 &&
      while ! curl -s http://localhost:9000/minio/health/ready; do sleep 1; done &&
      /usr/local/bin/create-bucket.sh &&
      wait
      "
volumes:
  pgdata:
    driver: local
