"""add author column

Revision ID: ac84e66bf754
Revises: 992f51423471
Create Date: 2024-12-22 19:55:26.569222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac84e66bf754'
down_revision: Union[str, None] = '992f51423471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report', 'user', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'author_id')
    # ### end Alembic commands ###
